name: Varo_Plugin
author: Wuffi2405&FraFrieFa
version: 0.1.2 [Alpha 1.2]
description: varo
main: de.wuffitv.varo.Main
commands:
  google:
    usage: /google
  start:
    usage: /start
  remove:
    usage: /remove
  bereit:
    usage: /bereit
  refresh:
    usage: /refresh
  online:
    usage: /online
  varo:
    usage: /varo