name: Varo_Plugin
author: Wuffi2405&FraFrieFa
version: 1.1.0
description: varo
main: de.wuffitv.varo.Main
commands:
  google:
    usage: /google
  start:
    usage: /start
  remove:
    usage: /remove
  bereit:
    usage: /bereit
  refresh:
    usage: /refresh